import {mountDeviceFeatures} from './device-features.js';
import { CONFIG as C } from './config.js';
import { translations } from './translations.js';
import { messageBody } from './media.js';
import { installCalls } from './calls.js';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let lang=C.locale, chat=null, busy=false, calls=null, timer=null, page='home', pending=null,refreshing=false,lastRead=0;
const t=k=>translations[lang][k];
const root=$('#app');
function shell(){document.documentElement.lang=lang;document.title=C.name;document.documentElement.style.setProperty('--brand',C.color);document.documentElement.style.setProperty('--accent',C.accent);$('#brand').textContent=C.name;$('#country').textContent=C.country;$('#motto').textContent=t('tagline');$('#badge').textContent=C.preview?t('preview'):t('live');$('#privacy').textContent=t('privacy');$('#privacy').onclick=privacy;$('#language').setAttribute('aria-label',t('language'));$('#language').innerHTML=C.languages.map(l=>`<option value="${l}" ${l===lang?'selected':''}>${esc(C.languageNames[l])}</option>`).join('');$('#language').disabled=!!chat;$('#language').onchange=e=>{lang=e.target.value;shell();page==='details'?details():home();};}
function notify(message){$('#status').textContent=message;}
function button(id,label,cls='primary'){return `<button id="${id}" class="${cls}">${esc(label)}</button>`;}
function dialog(title,body,actions){const d=$('#dialog');d.innerHTML=`<h2>${esc(title)}</h2>${body}<div class="actions">${actions||button('close-dialog',t('close'),'secondary')}</div>`;d.showModal();if($('#close-dialog'))$('#close-dialog').onclick=()=>d.close();}
function privacy(){dialog(t('privacy'),`<p>${esc(C.preview?t('privacyText'):t('livePrivacy'))}</p><p>${esc(t('chart'))}</p>`);}
function culture(){const v=C.culture[lang]||C.culture.en;return `<div class="culture-grid"><article><span class="section-number">01</span><h3>${esc(v[0])}</h3><p>${esc(v[1])}</p></article><article><span class="section-number">02</span><h3>${esc(v[2])}</h3><p>${esc(v[3])}</p></article></div>`;}
function home(){page='home';root.innerHTML=`<section class="welcome"><div class="orbit" aria-hidden="true"><span>${C.symbol}</span><i></i><b>✦</b></div><span class="eyebrow">${esc(C.native)}</span><h1>${esc(t('tagline'))}</h1><p class="lead">${esc(C.culture[lang]?.[0]||C.tradition)}</p>${button('begin',t('begin'))}<p class="fine">${esc(t('notice'))}</p></section><section class="traditions"><h2>${esc(t('traditions'))}</h2>${culture()}</section>`;$('#begin').onclick=details;}
function details(){page='details';const cutoff=new Date();cutoff.setUTCFullYear(cutoff.getUTCFullYear()-18);root.innerHTML=`<section class="profile"><span class="eyebrow">${esc(C.native)}</span><h1>${esc(t('profile'))}</h1><form id="profile-form"><label>${esc(t('name'))}<input name="name" maxlength="60" autocomplete="given-name" required></label><label>${esc(t('dob'))}<input type="date" name="dob" min="1900-01-01" max="${cutoff.toISOString().slice(0,10)}" required></label><p class="note">${esc(t('chart'))}</p><label class="check"><input type="checkbox" name="consent" required><span>${esc(t('consent'))}</span></label><p class="fine">${esc(C.preview?t('privacyText'):t('livePrivacy'))}</p><button class="primary" type="submit">${esc(t('start'))} <span aria-hidden="true">↗</span></button><button type="button" class="secondary" id="back">${esc(t('back'))}</button></form></section>`;$('#back').onclick=home;$('#profile-form').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;const submit=e.target.querySelector('[type=submit]');submit.disabled=true;const f=new FormData(e.target);try{if(C.preview)chat={id:crypto.randomUUID(),name:f.get('name'),language:lang,freeUsed:0,entitlement:'free',messages:[{id:1,role:'assistant',kind:'welcome',body:t('welcome'),created:Date.now()}]};else chat=await api('/api/start','POST',{name:f.get('name'),dob:f.get('dob'),consent:true,language:lang,preferences:{remember:false,location:null}});renderChat();}catch(err){notify(err.message);}finally{busy=false;if(submit.isConnected)submit.disabled=false;}};}
async function api(route,method='GET',body){const r=await fetch(route,{method,credentials:'same-origin',cache:'no-store',headers:body===undefined?{}:{'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(40000)});let value;try{value=await r.json();}catch{throw Error(t('error'));}if(!r.ok)throw Object.assign(Error(value.error||t('error')),{status:r.status});return value;}
function renderChat(){page='chat';lang=chat.language;shell();root.innerHTML=`<section class="conversation"><header class="chat-head"><div class="avatar">${C.symbol}</div><div><h1>${esc(C.name)}</h1><span>${esc(t('chat'))}</span></div><button id="chat-options" class="round" aria-label="${esc(t('privacy'))}">⋯</button></header><div class="chat-scroll" id="messages" role="log" aria-live="polite" aria-label="${esc(t('chat'))}"></div><p id="waiting" class="fine"></p><form id="composer"><label class="sr-only" for="message-input">${esc(t('message'))}</label><textarea id="message-input" maxlength="2000" rows="2" required placeholder="${esc(t('message'))}"></textarea><button type="submit" class="primary">${esc(t('send'))} ↑</button></form><div class="tools">${!C.preview?`<label class="attachment">${esc(t('attach'))}<input id="upload" type="file" accept="image/jpeg,image/png,image/webp,video/mp4,audio/mpeg,audio/wav,audio/webm,application/pdf"></label>`:''}<button id="show-traditions" class="secondary">${esc(t('traditions'))}</button></div><p class="fine bottom-note">${esc(t('notice'))}</p></section>`;mountDeviceFeatures($('.tools'),notify);$('#composer').onsubmit=send;$('#message-input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('#composer').requestSubmit();}};$('#show-traditions').onclick=()=>dialog(t('traditions'),culture());$('#chat-options').onclick=options;if(!C.preview){$('#upload').onchange=upload;calls?.destroy();calls=installCalls({role:'customer',getConversationId:()=>chat.id,notify});calls.mount($('.chat-head'));calls.poll();clearInterval(timer);timer=setInterval(refresh,3000);}draw();}
function draw(){const box=$('#messages');if(!box)return;const oldTop=box.scrollTop,near=box.scrollHeight-box.scrollTop-box.clientHeight<100;box.innerHTML=chat.messages.filter(m=>m.role!=='system').map(m=>`<article class="bubble ${m.role==='user'?'mine':''}" data-message="${Number(m.id)}"><span class="sender">${esc(m.role==='user'?chat.name:C.name)}</span>${m.deleted?'<em>—</em>':m.kind==='media'?messageBody(m):`<p>${esc(m.body)}</p>`}<time>${esc(new Intl.DateTimeFormat(lang,{hour:'2-digit',minute:'2-digit'}).format(new Date(m.created)))}</time></article>`).join('');box.scrollTop=near?box.scrollHeight:oldTop;$('#waiting').textContent=chat.messages.some(m=>m.status==='pending')?t('wait'):'';}
async function send(e){e.preventDefault();if(busy)return;const input=$('#message-input'),body=input.value.trim();if(!body)return;if(!pending||pending.body!==body)pending={body,clientId:crypto.randomUUID()};busy=true;$('#composer button').disabled=true;try{if(C.preview){chat.messages.push({id:Date.now(),role:'user',kind:'customer',body,created:Date.now()});chat.messages.push({id:Date.now()+1,role:'assistant',kind:'demo',body:t(['sample','sample2','sample3'][chat.freeUsed++%3]),created:Date.now()});}else chat=await api('/api/messages','POST',pending);pending=null;input.value='';notify('');draw();}catch(err){if(err.status===402)offer();else notify(err.message);}finally{busy=false;$('#composer button').disabled=false;input.focus();}}
function offer(){dialog(t('unlock'),`<p>${esc(t('notice'))}</p>`,button('unlock',t('unlock'))+button('close-dialog',t('cancel'),'secondary'));$('#unlock').onclick=async()=>{try{chat=await api('/api/payment/demo','POST',{});$('#dialog').close();notify(t('unlocked'));draw();}catch(e){notify(e.message);}};}
async function refresh(){if(document.hidden||busy||refreshing||C.preview||page!=='chat')return;refreshing=true;try{const next=await api('/api/chat');if(JSON.stringify(next)!==JSON.stringify(chat)){chat=next;draw();}const newest=Math.max(0,...chat.messages.map(m=>m.id));if(newest>lastRead){await api('/api/chat/read','POST',{lastId:newest});lastRead=newest;}}catch(e){notify(e.message);}finally{refreshing=false;}}
async function upload(){const file=$('#upload').files[0];if(!file||busy)return;if(file.size>20*1024*1024){notify('Maximum 20 MB');return;}busy=true;try{const response=await fetch('/api/uploads?name='+encodeURIComponent(file.name),{method:'POST',credentials:'same-origin',headers:{'Content-Type':file.type},body:file,signal:AbortSignal.timeout(60000)});const item=await response.json();if(!response.ok)throw Error(item.error||t('error'));chat=await api('/api/messages','POST',{body:'',mediaIds:[item.id],clientId:crypto.randomUUID()});draw();}catch(e){notify(e.message);}finally{busy=false;$('#upload').value='';}}
function options(){dialog(t('privacy'),`<p>${esc(C.preview?t('privacyText'):t('livePrivacy'))}</p>`,button('export-chat',t('export'),'secondary')+button('delete-chat',t('delete'),'danger')+button('close-dialog',t('close'),'secondary'));$('#export-chat').onclick=()=>{const text=chat.messages.filter(m=>!m.deleted).map(m=>`${m.role==='user'?chat.name:C.name}: ${m.kind==='media'?'[Attachment]':m.body}`).join('\n\n');const blob=new Blob([text],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=C.id+'-conversation.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);};$('#delete-chat').onclick=()=>{dialog(t('delete'),`<p>${esc(t('deleteConfirm'))}</p>`,button('confirm-delete',t('delete'),'danger')+button('close-dialog',t('cancel'),'secondary'));$('#confirm-delete').onclick=async()=>{try{if(!C.preview)await api('/api/chat','DELETE');chat=null;pending=null;clearInterval(timer);calls?.destroy();calls=null;$('#dialog').close();shell();home();notify('');}catch(e){notify(e.message);}};};}
// Android WebView cannot download a blob URL without a privileged native bridge.
// Keep export available as selectable text without granting a JavaScript bridge.
document.addEventListener('click',event=>{if(location.hostname==='appassets.androidplatform.net'&&event.target.closest('#export-chat')){event.preventDefault();event.stopImmediatePropagation();const text=chat.messages.filter(m=>!m.deleted).map(m=>`${m.role==='user'?chat.name:C.name}: ${m.kind==='media'?'[Attachment]':m.body}`).join('\n\n');dialog(t('export'),`<textarea rows="12" readonly aria-label="${esc(t('export'))}">${esc(text)}</textarea>`);}},true);
shell();home();
if(!C.preview)api('/api/chat').then(value=>{chat=value;renderChat();}).catch(e=>{if(e.status!==401)notify(e.message);});
if('serviceWorker'in navigator&&location.protocol==='https:'&&C.preview&&location.hostname!=='appassets.androidplatform.net')navigator.serviceWorker.register('./sw.js').catch(()=>{});
