import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { apps,languageNames } from '../apps/catalog.mjs';
import { translations } from '../shared/translations.mjs';
export const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const write=(p,data)=>{const full=path.join(root,p);fs.mkdirSync(path.dirname(full),{recursive:true});fs.writeFileSync(full,data);};
const json=value=>JSON.stringify(value).replaceAll('<','\\u003c');
const html=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=c=>`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><rect width="512" height="512" rx="110" fill="${c.color}"/><circle cx="256" cy="256" r="164" fill="none" stroke="${c.accent}" stroke-width="3"/><circle cx="256" cy="256" r="124" fill="none" stroke="${c.accent}" stroke-width="2"/><path d="M256 118 287 225 394 256 287 287 256 394 225 287 118 256 225 225Z" fill="${c.accent}"/><circle cx="376" cy="126" r="13" fill="#fff9ed"/></svg>`;
const template=c=>`<!doctype html><html lang="${c.locale}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="${c.color}"><meta name="description" content="${html(c.name+' — '+c.country+' astrology-themed conversations and reflection')}"><link rel="icon" href="./icon.svg"><link rel="manifest" href="./manifest.webmanifest"><link rel="stylesheet" href="./style.css"><link rel="stylesheet" href="./calls.css"><title>${html(c.name)}</title><script type="module" src="./app.js"></script></head><body><header class="top"><span class="brand-mark" aria-hidden="true">${c.symbol}</span><div><span id="brand">${html(c.name)}</span><span id="country">${html(c.country)}</span></div><select id="language" aria-label="Language"></select></header><div class="preview-strip" id="badge"></div><div id="status" role="alert"></div><main id="app"></main><footer><span id="motto"></span><button id="privacy">Privacy</button></footer><dialog id="dialog"></dialog><noscript>Please enable JavaScript to use this app.</noscript></body></html>`;
const customerFiles=['app.js','style.css','media.js','media.css','calls.js','calls.css','voice-effects.js','device-features.js'];
const ownerFiles=['admin.html','admin.js','admin.css','library.js','workflow-admin.js','workflow.css'];
const rebrand=(text,c)=>text.replaceAll('Rekha Astrology',c.name).replace(/\bRekha\b/g,c.name).replaceAll('₹49','preview access').replaceAll('/icon-192.png','/icon.svg').replace(/<a class="install-owner"[^>]*>[^<]*<\/a>/g,'').replaceAll('private admin app','private owner panel').replace(/\bKundli\b/g,'Birth chart');
function publicFiles(c,preview){const cfg={...c,languageNames,preview};const files={'index.html':template(c),'config.js':`export const CONFIG = ${json(cfg)};\n`,'translations.js':read('shared/translations.mjs'),'icon.svg':icon(c),'manifest.webmanifest':json({id:'./',name:c.name,short_name:c.name,lang:c.locale,start_url:'./',scope:'./',display:'standalone',background_color:'#faf8f1',theme_color:c.color,icons:[{src:'./icon.svg',sizes:'any',type:'image/svg+xml',purpose:'any maskable'}]})};for(const f of customerFiles)files[f]=rebrand(read('shared/'+f),c);if(!preview)for(const f of ownerFiles)files[f]=rebrand(read('shared/'+f),c);else files['admin.html']=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="./style.css"><title>${html(c.name)} owner setup</title><main class="profile"><h1>${html(c.name)} owner controls</h1><p>This is an offline preview. Messages entered here stay on the customer device and do not reach an owner inbox.</p><p>Deploy the included backend and set its owner password to enable private messaging and the owner panel. See the repository's deployment guide.</p><a href="../../control.html">All app controls</a></main></html>`;files['sw.js']=`const CACHE=${json(c.id+'-preview-v2')};const FILES=${json(Object.keys(files).filter(f=>f!=='admin.html').map(f=>'./'+f))};self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(FILES))));self.addEventListener('activate',e=>e.waitUntil(self.clients.claim()));self.addEventListener('fetch',e=>{const u=new URL(e.request.url);if(e.request.method==='GET'&&u.origin===location.origin&&FILES.some(f=>new URL(f,self.registration.scope).pathname===u.pathname))e.respondWith(fetch(e.request).catch(()=>caches.match(e.request)));});`;return files;}
export function bundleWorker(c,files){
 let worker=read('backend/worker.mjs');
 worker=worker.replace(/^const welcome=.*;\r?$/m,`const welcome=Object.fromEntries(APP_CONFIG.languages.map(l=>[l,translations[l].welcome]));`)
 .replace("['en','hi','hinglish'].includes(data.language)",'APP_CONFIG.languages.includes(data.language)')
 .replace("generateReply({aiMode:'demo'},chat,await messages(id))","generateReply({aiMode:env.AI_MODE||'manual',aiBase:env.AI_BASE_URL,aiKey:env.AI_API_KEY,aiModel:env.AI_MODEL},chat,await messages(id))")
 .replace("{aiMode:'demo',paymentMode:'demo',freeTurns:3,amount:4900,retentionDays:30,rewardsEnabled:false}","{aiMode:env.AI_MODE||'manual',paymentMode:'demo',freeTurns:3,amount:0,currency:APP_CONFIG.currency,retentionDays:30,rewardsEnabled:false}")
 .replace("build:'rekha-workflow-0.5.1'","build:'global-1.0.0-preview',app:APP_CONFIG.id")
 .replace("const downloadHost=url.hostname==='rekhaastrology.in';","const downloadHost=false;")
 .replace("let asset=url.pathname;","let asset=url.pathname==='/'?'/index.html':url.pathname;")
 .replace('env.ASSETS.fetch(new Request(target,request))','staticAssetFetch(new Request(target,request))');
 const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.webmanifest':'application/manifest+json'};
 const assets=Object.fromEntries(Object.entries(files).map(([name,text])=>['/'+name,{type:mime[path.extname(name)]||'text/plain',base64:Buffer.from(text).toString('base64')}]));
 const staticCode=`const bundledAssets=${JSON.stringify(assets)};async function staticAssetFetch(request){if(!['GET','HEAD'].includes(request.method))return new Response('Method not allowed',{status:405});let p=new URL(request.url).pathname;if(p==='/')p='/index.html';const a=bundledAssets[p];if(!a)return new Response('Not found',{status:404});return new Response(request.method==='HEAD'?null:Uint8Array.from(atob(a.base64),c=>c.charCodeAt(0)),{headers:{'Content-Type':a.type}});}\n`;
 const clean=text=>text.replace(/^import .*;\r?\n/gm,'').replace(/export (async function|function|const)/g,'$1');
 let workflow=read('backend/workflow.mjs');const defaults={enabled:false,paymentEnabled:false,revision:0,timings:{firstDelayMs:5000,itemGapMs:5000,reminderDelayMs:60000,mediaDelayMs:3600000},assets:{firstVideo:null,testimonials:null,kundli:null,solution:null,puja:null,voice:null,qr:null},translations:{en:{},hinglish:{}},content:{greeting:translations[c.locale].welcome,firstCaption:'Introduction',testimonialsCaption:'Shared experiences',final:translations[c.locale].chart,reminder:translations[c.locale].message,kundliCaption:translations[c.locale].notice,solutionCaption:'Optional reflection',pujaCaption:'Optional cultural context',qrCaption:'Payments are disabled.'}};
 workflow=workflow.replace(/^export const workflowDefaults=.*;\r?$/m,`export const workflowDefaults=${json(defaults)};`);
 return `const APP_CONFIG=${json(c)};\n`+clean(read('shared/translations.mjs'))+'\n'+staticCode+['backend/ai.mjs','backend/rewards.mjs','backend/messaging.mjs','backend/calls.mjs',workflow,'backend/owner.mjs',worker].map(v=>clean(rebrand(v.startsWith('backend/')?read(v):v,c))).join('\n');
}
export function build(){
 for(const c of apps){
  const preview=publicFiles(c,true),live=publicFiles(c,false);
  for(const [name,text]of Object.entries(preview))write(`dist/web/${c.id}/${name}`,text);
  for(const [name,text]of Object.entries(live))write(`live/${c.id}/public/${name}`,text);
  write(`live/${c.id}/worker.mjs`,bundleWorker(c,live));
  write(`live/${c.id}/schema.sql`,read('backend/schema.sql').replace("DEFAULT 'ai'","DEFAULT 'manual'"));
  write(`live/${c.id}/wrangler.example.json`,JSON.stringify({name:'rekha-'+c.id,main:'worker.mjs',compatibility_date:'2026-09-24',workers_dev:true,d1_databases:[{binding:'DB',database_name:'rekha-'+c.id,database_id:'REPLACE_WITH_NEW_DATABASE_ID'}],r2_buckets:[{binding:'MEDIA',bucket_name:'rekha-'+c.id+'-media'}],vars:{AI_MODE:'manual',AD_REWARDS_ENABLED:'false'},triggers:{crons:['17 2 * * *','* * * * *']}},null,2));
 }
 const cards=apps.map(c=>`<article class="app-card" style="--brand:${c.color}"><span class="mark">${c.symbol}</span><p>${html(c.country)} · ${c.languages.map(l=>html(languageNames[l])).join(' / ')}</p><h2>${html(c.name)}</h2><p>${html(c.tradition)}</p><a href="./web/${c.id}/">Open web app ↗</a><a href="./apks/${c.id}.apk">Android APK ↓</a><a href="https://github.com/phukonbastab2-netizen/rekha/tree/main/global-apps/apps">Edit on GitHub</a></article>`).join('');
 const hub=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="./style.css"><title>Rekha Global · 12 country apps</title><main class="hub"><span class="eyebrow">REKHA GLOBAL COLLECTION · 01</span><h1>A world of stars.<br>Twelve personal spaces.</h1><p class="lead">12 web apps and Android previews, managed in your Rekha GitHub repository.</p><p class="note">These previews use sample replies on your device. They do not send messages to an astrologer, charge money or calculate charts. The repository includes the connected backend and private owner inbox for deployment.</p><p><a href="./control.html">Owner control centre ↗</a> · <a href="https://github.com/phukonbastab2-netizen/rekha/tree/main/global-apps">GitHub source ↗</a></p><div class="app-grid">${cards}</div></main></html>`;
 write('dist/index.html',hub);write('dist/style.css',read('shared/style.css'));write('dist/media.css',read('shared/media.css'));
 write('dist/control.html',`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="./style.css"><title>Rekha Global · owner controls</title><main class="hub"><span class="eyebrow">OWNER WORKSPACE</span><h1>Your apps. Your control.</h1><section id="voice-demo"><h2>Try the admin voice effects</h2><p>Natural, Warm, Bright, Radio and Robot. Local microphone test only; calls require the connected backend.</p></section><script type="module" src="./owner-voice-demo.js"></script><p class="lead">The public screen below manages source links and previews. Customer inboxes require the private backend.</p><p class="note">Edit names, colours and country text in apps/catalog.mjs; customer wording in shared/translations.mjs. Run npm run build, then rebuild Android previews. Every connected app uses its own database, storage bucket and owner password. Follow docs/DEPLOYMENT.md before receiving customer information.</p><p><a href="https://github.com/phukonbastab2-netizen/rekha/tree/main/global-apps">Open repository ↗</a> · <a href="./index.html">App collection ↗</a></p><div class="app-grid">${cards}</div></main></html>`);
 write('dist/owner-voice-demo.js',"import {mountDeviceFeatures} from './device-features.js';mountDeviceFeatures(document.querySelector('#voice-demo'),()=>{},true);");write('dist/device-features.js',read('shared/device-features.js'));write('dist/voice-effects.js',read('shared/voice-effects.js'));write('dist/.nojekyll','');write('dist/catalog.json',JSON.stringify(apps,null,2));
 console.log(`Built ${apps.length} offline web apps and ${apps.length} connected server packages.`);
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))build();
