// In-app only: this module never calls WhatsApp or a payment provider.
const wfClock=ctx=>typeof ctx.now==='function'?ctx.now():Date.now();
const wfTypes={firstVideo:'video',testimonials:'video',kundli:'image',solution:'image',puja:'image',voice:'audio',qr:'image'};
const wfContentFields=['greeting','firstCaption','testimonialsCaption','final','reminder','kundliCaption','solutionCaption','pujaCaption','qrCaption'];
export const workflowDefaults={enabled:false,paymentEnabled:false,revision:0,timings:{firstDelayMs:5000,itemGapMs:5000,reminderDelayMs:60000,mediaDelayMs:3600000},assets:{firstVideo:null,testimonials:null,kundli:null,solution:null,puja:null,voice:null,qr:null},translations:{en:{},hinglish:{}},content:{greeting:'🙏 नमस्ते। Rekha Astrology में आपका स्वागत है। अपना प्रश्न साझा कीजिए।',firstCaption:'पहले यह परिचय वीडियो देखिए और अपना प्रश्न साझा कीजिए।',testimonialsCaption:'ग्राहकों के साझा अनुभव',final:'अपना पूरा नाम, जन्म तिथि और प्रश्न साझा कीजिए। पूरी कुंडली के लिए जन्म समय और जन्म स्थान भी चाहिए। ₹49 का अनलॉक अभी भुगतान परीक्षण है; कोई वास्तविक शुल्क नहीं लिया जाता।',reminder:'कृपया अपना पूरा नाम, जन्म तिथि और प्रश्न साझा कीजिए। ₹49 का अनलॉक अभी भुगतान परीक्षण है; कोई वास्तविक शुल्क नहीं लिया जाता।',kundliCaption:'उदाहरण कुंडली — आपकी गणना की हुई कुंडली नहीं।',solutionCaption:'साझा मार्गदर्शन का उदाहरण। यह आपके लिए व्यक्तिगत गणना या निश्चित भविष्यवाणी नहीं है।',pujaCaption:'पूजा की सामग्री की साझा जानकारी। यह व्यक्तिगत अनिवार्य उपाय या भुगतान अनुरोध नहीं है।',qrCaption:'भुगतान इस पूर्वावलोकन में सक्रिय नहीं है।'}};
export async function workflowGetConfig(ctx){const row=await ctx.one("SELECT value FROM workflow_settings WHERE key='config'");return row?JSON.parse(row.value):structuredClone(workflowDefaults);}
export async function workflowIsEnrolled(one,id){return !!await one('SELECT 1 FROM chat_workflow WHERE conversation_id=?',id);}
function wfLocalized(config,language){const price=config.unlockPriceRupees??49;return Object.fromEntries(Object.entries({...config.content,...(config.translations?.[language]||{})}).map(([key,value])=>[key,value.replaceAll('{price}',String(price)).replace(/₹\s*49(?![\d०-९])/gu,`₹${price}`)]));}
function wfSteps(config,language,kind){const text=wfLocalized(config,language);if(kind==='first')return[{text:text.greeting}, {text:text.firstCaption,asset:'firstVideo'}, {text:text.testimonialsCaption,asset:'testimonials'}, {text:text.final}];if(kind==='reminder')return[{text:text.reminder}];return[{text:text.kundliCaption,asset:'kundli'},{text:text.solutionCaption,asset:'solution'},{text:text.pujaCaption,asset:'puja'},{text:'',asset:'voice'}];}
async function wfValidate(ctx,config){
  const {fail,one}=ctx;if(typeof config.enabled!=='boolean'||config.paymentEnabled!==false)throw fail(409,'Real payments are not configured. Keep paymentEnabled false.');
  for(const [key,value]of Object.entries(config.timings)){if(!['firstDelayMs','itemGapMs','reminderDelayMs','mediaDelayMs'].includes(key)||!Number.isSafeInteger(value)||value<0||value>7*86400000)throw fail(400,'Invalid workflow delay.');}
  for(const texts of [config.content,config.translations.en,config.translations.hinglish])for(const [key,value]of Object.entries(texts))if(!wfContentFields.includes(key)||typeof value!=='string'||!value.trim()||value.length>4000)throw fail(400,'Workflow text must contain 1–4,000 characters.');
  for(const key of Object.keys(config.assets))if(!(key in wfTypes))throw fail(400,'Unknown workflow asset.');
  for(const [key,type]of Object.entries(wfTypes)){const id=config.assets[key];if(id==null){if(config.enabled&&key!=='qr')throw fail(400,'Choose all six workflow media assets before enabling.');continue;}if(typeof id!=='string'||!/^[a-f0-9-]{36}$/.test(id))throw fail(400,'Choose media from your private library.');const media=await one('SELECT * FROM media_items WHERE id=?',id);if(config.enabled&&(!media||media.type!==type||!media.object_key||(key!=='qr'&&media.archived)))throw fail(400,'A workflow asset is unavailable or has the wrong type.');}
}
async function wfEnroll(ctx,chat,config,restart=false){
  const now=wfClock(ctx),existing=await ctx.one('SELECT generation FROM chat_workflow WHERE conversation_id=?',chat.id),generation=existing?(restart?existing.generation+1:existing.generation):1;
  if(existing&&!restart)return false;
  const snapshot={...config,unlockPriceRupees:ctx.appSettings?.service?.unlockPriceRupees??49,language:chat.language};
  await ctx.env.DB.batch([ctx.stmt("INSERT INTO chat_workflow(conversation_id,generation,status,stage,campaign,config,started_at,updated) VALUES(?,?,'armed','NEW','NONE',?,?,?) ON CONFLICT(conversation_id) DO UPDATE SET generation=excluded.generation,status=excluded.status,stage=excluded.stage,campaign=excluded.campaign,config=excluded.config,started_at=excluded.started_at,updated=excluded.updated",chat.id,generation,JSON.stringify(snapshot),now,now),ctx.stmt("UPDATE workflow_jobs SET status='cancelled',lease_until=NULL,updated=? WHERE conversation_id=? AND generation!=? AND status IN ('pending','processing','failed')",now,chat.id,generation)]);return true;
}
export async function flowOnStart(ctx,chat){const config=await workflowGetConfig(ctx);if(!config.enabled)return false;await wfValidate(ctx,config);return wfEnroll(ctx,chat,config);}
function wfJob(ctx,flow,chat,kind,due,triggerId=null){const config=JSON.parse(flow.config),now=wfClock(ctx);return ctx.stmt("INSERT OR IGNORE INTO workflow_jobs(id,conversation_id,generation,kind,status,due,payload,trigger_id,created,updated) SELECT ?,?,?,?,'pending',?,?,?,?,? WHERE EXISTS(SELECT 1 FROM chat_workflow WHERE conversation_id=? AND generation=?)",crypto.randomUUID(),chat.id,flow.generation,kind,due,JSON.stringify({steps:wfSteps(config,config.language||chat.language,kind),assets:config.assets,timings:config.timings}),triggerId,now,now,chat.id,flow.generation);}
async function wfStartFirst(ctx,flow,chat,triggerId=null){const now=wfClock(ctx);await ctx.env.DB.batch([wfJob(ctx,flow,chat,'first',now,triggerId),ctx.stmt("UPDATE chat_workflow SET stage='FIRST_SEQUENCE',status=CASE WHEN status='paused' THEN status ELSE 'active' END,updated=? WHERE conversation_id=? AND generation=? AND stage='NEW'",now,chat.id,flow.generation)]);}
export async function flowOnCustomer(ctx,chat,message){
  const flow=await ctx.one('SELECT * FROM chat_workflow WHERE conversation_id=?',chat.id);if(!flow||!message||message.role!=='user'||message.conversation_id!==chat.id||message.created<flow.started_at||await ctx.one('SELECT 1 FROM workflow_events WHERE conversation_id=? AND generation=? AND message_id=?',chat.id,flow.generation,message.id))return false;
  const now=wfClock(ctx),config=JSON.parse(flow.config),statements=[ctx.stmt('INSERT OR IGNORE INTO workflow_events(conversation_id,generation,message_id,created) VALUES(?,?,?,?)',chat.id,flow.generation,message.id,now)];
  if(flow.stage==='NEW')statements.push(wfJob(ctx,flow,chat,'first',now,message.id),ctx.stmt("UPDATE chat_workflow SET stage='FIRST_SEQUENCE',status=CASE WHEN status='paused' THEN status ELSE 'active' END,updated=? WHERE conversation_id=? AND generation=? AND stage='NEW'",now,chat.id,flow.generation));
  if(flow.stage==='WAITING_FOR_DETAILS')statements.push(wfJob(ctx,flow,chat,'reminder',now+config.timings.reminderDelayMs,message.id),ctx.stmt("UPDATE chat_workflow SET stage='REMINDER_SCHEDULED',updated=? WHERE conversation_id=? AND generation=? AND stage='WAITING_FOR_DETAILS'",now,chat.id,flow.generation));
  if(message.kind==='media'&&flow.campaign==='NONE')statements.push(wfJob(ctx,flow,chat,'media',now+config.timings.mediaDelayMs,message.id),ctx.stmt("UPDATE chat_workflow SET campaign='SCHEDULED',updated=? WHERE conversation_id=? AND generation=? AND campaign='NONE'",now,chat.id,flow.generation));
  await ctx.env.DB.batch(statements);return true;
}
export async function workflowChatView(ctx,id){
  const {one,all}=ctx,chat=await one('SELECT c.mode,COALESCE(s.blocked,0) AS blocked FROM conversations c LEFT JOIN chat_messaging s ON s.conversation_id=c.id WHERE c.id=?',id),flow=await one('SELECT * FROM chat_workflow WHERE conversation_id=?',id),config=await workflowGetConfig(ctx);
  if(!chat)throw ctx.fail(404,'Conversation not found.');
  if(!flow)return{enrolled:false,status:'not-started',stage:'NEW',campaign:'NONE',nextDue:null,pauseReason:null,jobs:[]};
  const jobs=await all('SELECT id,kind,step,status,due,attempts FROM workflow_jobs WHERE conversation_id=? AND generation=? ORDER BY created,id',id,flow.generation),next=jobs.filter(j=>['pending','processing'].includes(j.status)).sort((a,b)=>a.due-b.due)[0];
  return{enrolled:true,status:flow.status,stage:flow.stage,campaign:flow.campaign,generation:flow.generation,pauseReason:!config.enabled?'global-disabled':chat.blocked?'customer-blocked':flow.status==='paused'?'owner-paused':chat.mode!=='ai'?'reply-mode-'+chat.mode:null,nextDue:next?.due??null,jobs};
}
export async function workflowRoutes(ctx){
  const {route,method,owner,body,result,one,get,stmt,fail}=ctx;
  if(route==='/api/admin/workflow/settings'){
    await owner();const current=await workflowGetConfig(ctx);if(method==='GET')return result(current);if(method!=='PATCH')throw fail(405,'Method not allowed.');const data=await body(),next={...current,...('enabled' in data?{enabled:data.enabled}:{}),...('paymentEnabled' in data?{paymentEnabled:data.paymentEnabled}:{}),timings:{...current.timings,...data.timings},assets:{...current.assets,...data.assets},content:{...current.content,...data.content},translations:{en:{...current.translations.en,...data.translations?.en},hinglish:{...current.translations.hinglish,...data.translations?.hinglish}},revision:current.revision+1};await wfValidate(ctx,next);await stmt("INSERT INTO workflow_settings(key,value) VALUES('config',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",JSON.stringify(next)).run();return result(next);
  }
  const match=route.match(/^\/api\/admin\/conversations\/([a-f0-9-]{36})\/workflow$/);if(!match)return null;await owner();const chat=await get(match[1]);if(!chat)throw fail(404,'Conversation not found.');if(method==='GET')return result(await workflowChatView(ctx,chat.id));if(method!=='PATCH')throw fail(405,'Method not allowed.');const data=await body();if(!['start','pause','resume','restart'].includes(data.action))throw fail(400,'Choose start, pause, resume or restart.');let flow=await one('SELECT * FROM chat_workflow WHERE conversation_id=?',chat.id);
  if(data.action==='start'||data.action==='restart'){const config=await workflowGetConfig(ctx);if(!config.enabled)throw fail(409,'Enable the workflow and choose its media first.');await wfValidate(ctx,config);if(data.action==='start'&&flow)throw fail(409,'This workflow is already enrolled. Choose resume or restart.');await wfEnroll(ctx,chat,config,data.action==='restart');flow=await one('SELECT * FROM chat_workflow WHERE conversation_id=?',chat.id);await wfStartFirst(ctx,flow,chat);}
  else{if(!flow)throw fail(409,'Start this chat workflow first.');await stmt('UPDATE chat_workflow SET status=?,updated=? WHERE conversation_id=?',data.action==='pause'?'paused':flow.stage==='NEW'?'armed':'active',wfClock(ctx),chat.id).run();if(data.action==='resume')await stmt("UPDATE workflow_jobs SET status='pending',attempts=0,lease_until=NULL,due=MIN(due,?),updated=? WHERE conversation_id=? AND generation=? AND status='failed'",wfClock(ctx),wfClock(ctx),chat.id,flow.generation).run();}
  return result(await workflowChatView(ctx,chat.id));
}
export async function workflowProcessDue(ctx,options={}){
  const {env,one,all,stmt}=ctx,config=await workflowGetConfig(ctx);if(!config.enabled)return{sent:0};const now=wfClock(ctx),limit=Math.max(1,Math.min(options.limit||20,40)),chatFilter=options.chatId?' AND j.conversation_id=?':'',params=[now,now,...(options.chatId?[options.chatId]:[]),limit];
  const jobs=await all("SELECT j.* FROM workflow_jobs j JOIN chat_workflow f ON f.conversation_id=j.conversation_id AND f.generation=j.generation JOIN conversations c ON c.id=j.conversation_id LEFT JOIN chat_messaging s ON s.conversation_id=c.id WHERE (j.status='pending' OR (j.status='processing' AND j.lease_until<?)) AND j.due<=? AND f.status!='paused' AND c.mode='ai' AND COALESCE(s.blocked,0)=0"+chatFilter+' ORDER BY j.due,j.id LIMIT ?',...params);let sent=0;
  for(const job of jobs){
    const claimedAt=wfClock(ctx),lease=claimedAt+60000,claimed=await stmt("UPDATE workflow_jobs SET status='processing',lease_until=?,attempts=attempts+1,updated=? WHERE id=? AND step=? AND (status='pending' OR (status='processing' AND lease_until<?)) AND EXISTS(SELECT 1 FROM chat_workflow f JOIN conversations c ON c.id=f.conversation_id LEFT JOIN chat_messaging s ON s.conversation_id=c.id WHERE f.conversation_id=? AND f.generation=? AND f.status!='paused' AND c.mode='ai' AND COALESCE(s.blocked,0)=0) AND EXISTS(SELECT 1 FROM workflow_settings WHERE key='config' AND json_extract(value,'$.enabled')=1)",lease,claimedAt,job.id,job.step,claimedAt,job.conversation_id,job.generation).run();if(!claimed.meta.changes)continue;
    try{
      const payload=JSON.parse(job.payload),step=payload.steps[job.step];if(!step)throw Error('Invalid workflow step.');let media=null,body=step.text,kind='owner-message';if(step.asset){media=await one('SELECT * FROM media_items WHERE id=? AND archived=0',payload.assets[step.asset]);if(!media?.object_key||media.type!==wfTypes[step.asset])throw Error('Workflow media unavailable.');kind='media';body=JSON.stringify({text:step.text,title:'',items:[{id:media.id,title:media.title,type:media.type,url:'/api/media/'+media.id,mime:media.mime,size:media.size}]});}
      const clientId=`workflow:${job.generation}:${job.id}:${job.step}`,finished=job.step+1>=payload.steps.length,deliveredAt=wfClock(ctx),nextDue=deliveredAt+(job.kind==='first'&&job.step===0?payload.timings.firstDelayMs:payload.timings.itemGapMs),guard="EXISTS(SELECT 1 FROM workflow_jobs j JOIN chat_workflow f ON f.conversation_id=j.conversation_id AND f.generation=j.generation JOIN conversations c ON c.id=f.conversation_id LEFT JOIN chat_messaging s ON s.conversation_id=c.id WHERE j.id=? AND j.step=? AND j.status='processing' AND j.lease_until=? AND f.status!='paused' AND c.mode='ai' AND COALESCE(s.blocked,0)=0) AND EXISTS(SELECT 1 FROM workflow_settings WHERE key='config' AND json_extract(value,'$.enabled')=1)";
      const batch=await env.DB.batch([
        stmt("INSERT OR IGNORE INTO messages(conversation_id,role,kind,body,status,client_id,created) SELECT ?,'assistant',?,?,'sent',?,? WHERE "+guard,job.conversation_id,kind,body,clientId,deliveredAt,job.id,job.step,lease),
        ...(media?[stmt('INSERT OR IGNORE INTO media_grants(conversation_id,media_id) SELECT ?,? WHERE EXISTS(SELECT 1 FROM messages WHERE conversation_id=? AND client_id=?)',job.conversation_id,media.id,job.conversation_id,clientId)]:[]),
        stmt("UPDATE messages SET status='answered' WHERE conversation_id=? AND role='user' AND id<=? AND status IN ('pending','failed') AND EXISTS(SELECT 1 FROM messages WHERE conversation_id=? AND client_id=?)",job.conversation_id,job.trigger_id??-1,job.conversation_id,clientId),
        stmt('UPDATE conversations SET version=version+1,updated=? WHERE id=? AND EXISTS(SELECT 1 FROM messages WHERE conversation_id=? AND client_id=?)',deliveredAt,job.conversation_id,job.conversation_id,clientId),
        stmt('DELETE FROM drafts WHERE conversation_id=? AND EXISTS(SELECT 1 FROM messages WHERE conversation_id=? AND client_id=?)',job.conversation_id,job.conversation_id,clientId),
        stmt("UPDATE workflow_jobs SET step=step+1,status=?,due=?,lease_until=NULL,attempts=0,updated=? WHERE id=? AND step=? AND status='processing' AND lease_until=? AND EXISTS(SELECT 1 FROM messages WHERE conversation_id=? AND client_id=?)",finished?'done':'pending',nextDue,deliveredAt,job.id,job.step,lease,job.conversation_id,clientId),
        ...(finished?[stmt("UPDATE chat_workflow SET stage=CASE WHEN ?='first' THEN 'WAITING_FOR_DETAILS' WHEN ?='reminder' THEN 'REMINDER_SENT' ELSE stage END,campaign=CASE WHEN ?='media' THEN 'SENT' ELSE campaign END,updated=? WHERE conversation_id=? AND generation=? AND EXISTS(SELECT 1 FROM workflow_jobs WHERE id=? AND status='done')",job.kind,job.kind,job.kind,deliveredAt,job.conversation_id,job.generation,job.id)]:[]),
      ]);
      if(batch[0].meta.changes)sent++;
      const still=await one('SELECT status FROM workflow_jobs WHERE id=?',job.id);if(still?.status==='processing')await stmt("UPDATE workflow_jobs SET status='pending',lease_until=NULL,attempts=MAX(0,attempts-1),updated=? WHERE id=? AND status='processing' AND lease_until=?",wfClock(ctx),job.id,lease).run();
    }catch{await stmt("UPDATE workflow_jobs SET status=CASE WHEN attempts>=5 THEN 'failed' ELSE 'pending' END,due=?,lease_until=NULL,updated=? WHERE id=? AND status='processing' AND lease_until=?",now+Math.min(3600000,30000*2**Math.min(job.attempts,6)),now,job.id,lease).run();}
  }
  return{sent};
}
