import {splitSqlStatements} from '../cloudflare/sql-statements.mjs';
import { Miniflare, convertV4MiniflareOptions } from 'miniflare';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';
import path from 'node:path';
const root=path.resolve('.'),files=['cloudflare/rewards.mjs','cloudflare/messaging.mjs','cloudflare/calls.mjs','cloudflare/workflow.mjs','cloudflare/app-settings.mjs','cloudflare/owner.mjs','src/ai.mjs','cloudflare/kundli-followup.mjs','cloudflare/activity.mjs','cloudflare/worker.mjs'];
const script=files.map(name=>readFileSync(path.join(root,name),'utf8').replace(/^import .*;\r?\n/gm,'').replace(/export (async function|function|const)/g,'$1')).join('\n');
const mf=new Miniflare(convertV4MiniflareOptions({modules:true,script,compatibilityDate:'2026-09-24',d1Databases:{DB:'calls-test'},r2Buckets:{MEDIA:'calls-media'},bindings:{CUSTOMER_AUTOMATION_ENABLED:'true',ADMIN_PASSWORD_HASH:createHash('sha256').update('local-test-password').digest('hex')}}));
const db=await mf.getD1Database('DB');
for(const source of ['schema.sql','migration-calls.sql'])for(const sql of splitSqlStatements(readFileSync(path.join(root,'cloudflare',source),'utf8')))await db.prepare(sql).run();
async function call(route,method='GET',data,cookie='',headers={}){const response=await mf.dispatchFetch('https://rekha.test'+route,{method,headers:{Origin:'https://rekha.test','Content-Type':'application/json',Cookie:cookie,...headers},...(data===undefined?{}:{body:JSON.stringify(data)})});return{status:response.status,data:await response.json(),cookie:response.headers.get('Set-Cookie')?.split(';')[0]};}
try{
  const signup=()=>call('/api/start','POST',{name:'Calls test',dob:'1990-01-01',language:'en',consent:true,preferences:{}});
  const first=await signup(),second=await signup();assert.equal(first.status,201);const c=first.cookie,c2=second.cookie,id=first.data.id,id2=second.data.id;
  const login=await call('/api/admin/login','POST',{password:'local-test-password'});assert.equal(login.status,200);const a=login.cookie;
  assert.equal((await call('/api/calls')).status,401);assert.equal((await call('/api/admin/calls','GET',undefined,c)).status,401);
  assert.equal((await call('/api/calls/config','GET',undefined,c)).data.foregroundOnly,true);assert.equal((await call('/api/calls/config','GET',undefined,c)).data.relayConfigured,false);
  assert.equal((await call('/api/calls','POST',{type:'voice'},c,{Origin:'https://bad.test'})).status,403);
  assert.equal((await call('/api/calls','POST',{type:'conference'},c)).status,400);assert.equal((await call('/api/admin/calls','POST',{type:'voice'},a)).status,400);
  const outgoing=await call('/api/calls','POST',{type:'voice',conversationId:id2},c);assert.equal(outgoing.status,201,JSON.stringify(outgoing.data));assert.equal(outgoing.data.conversationId,id);const cid=outgoing.data.id;
  assert.equal((await call('/api/calls/'+cid,'GET',undefined,c2)).status,404);assert.equal((await call('/api/calls/'+cid+'/signals','GET',undefined,c2)).status,404);assert.equal((await call('/api/calls/'+cid+'/end','POST',{},c2)).status,404);
  assert.equal((await call('/api/calls/'+cid+'/accept','POST',{},c)).status,403);assert.equal((await call('/api/calls','POST',{type:'voice'},c)).status,409);
  const offer={kind:'offer',payload:{type:'offer',sdp:'v=0\r\ns=test offer\r\n',unexpected:'discard'}};
  assert.equal((await call('/api/admin/calls/'+cid+'/signals','POST',offer,a)).status,403);assert.equal((await call('/api/calls/'+cid+'/signals','POST',offer,c)).status,201);
  assert.equal((await call('/api/calls/'+cid+'/signals','POST',offer,c)).status,200);
  assert.equal((await call('/api/calls/'+cid+'/signals','POST',{kind:'offer',payload:{type:'offer',sdp:'v=0\r\ns=changed\r\n'}},c)).status,409);
  assert.equal((await call('/api/calls/'+cid+'/signals','GET',undefined,c)).data.signals.length,0);
  const received=(await call('/api/admin/calls/'+cid+'/signals','GET',undefined,a)).data;assert.equal(received.signals.length,1);assert.equal(received.signals[0].payload.sdp,offer.payload.sdp);assert.equal('unexpected' in received.signals[0].payload,false);
  assert.equal((await call('/api/admin/calls/'+cid+'/signals?after='+received.signals[0].id,'GET',undefined,a)).data.signals.length,0);
  assert.equal((await call('/api/admin/calls/'+cid+'/signals?after=-1','GET',undefined,a)).status,400);
  const answer={kind:'answer',payload:{type:'answer',sdp:'v=0\r\ns=test answer\r\n'}};
  assert.equal((await call('/api/admin/calls/'+cid+'/signals','POST',answer,a)).status,403);
  assert.equal((await call('/api/admin/calls/'+cid+'/accept','POST',{},a)).data.status,'active');assert.equal((await call('/api/admin/calls/'+cid+'/accept','POST',{},a)).status,409);
  assert.equal((await call('/api/admin/calls/'+cid+'/signals','POST',answer,a)).status,201);assert.equal((await call('/api/calls/'+cid+'/signals','GET',undefined,c)).data.signals[0].kind,'answer');
  assert.equal((await call('/api/calls','POST',{type:'video'},c2)).status,409);
  const ice={kind:'ice',payload:{candidate:'candidate:1 udp 2122260223 192.0.2.1 12345 typ host',sdpMid:'0',sdpMLineIndex:0,usernameFragment:'local',secret:'must not persist'}};
  assert.equal((await call('/api/calls/'+cid+'/signals','POST',ice,c)).status,201);
  const peerIce=(await call('/api/admin/calls/'+cid+'/signals','GET',undefined,a)).data.signals.find(s=>s.kind==='ice');assert.equal('secret' in peerIce.payload,false);assert.equal(peerIce.payload.sdpMLineIndex,0);
  assert.equal((await call('/api/calls/'+cid+'/signals','POST',{kind:'ice',payload:{candidate:'x',sdpMLineIndex:-1}},c)).status,400);
  assert.equal((await call('/api/calls/'+cid+'/signals','POST',{kind:'ice',payload:{candidate:'x',sdpMid:{bad:true}}},c)).status,400);
  assert.equal((await call('/api/calls/'+cid+'/signals','POST',{kind:'offer',payload:{type:'offer',sdp:'x'.repeat(14001)}},c)).status,400);
  assert.equal((await call('/api/calls/'+cid+'/end','POST',{reason:'cancelled'},c)).status,200);assert.equal((await call('/api/admin/calls/'+cid,'GET',undefined,a)).data.status,'ended');assert.equal((await call('/api/admin/calls/'+cid+'/signals','GET',undefined,a)).data.signals.length,0);
  assert.equal((await call('/api/calls/'+cid+'/signals','POST',ice,c)).status,409);
  const ownerRing=await call('/api/admin/calls','POST',{conversationId:id2,type:'video'},a);assert.equal(ownerRing.status,201);assert.equal(ownerRing.data.caller,'admin');assert.equal((await call('/api/calls','GET',undefined,c)).data.calls.length,0);assert.equal((await call('/api/calls','GET',undefined,c2)).data.calls[0].id,ownerRing.data.id);
  await call('/api/admin/conversations/'+id2+'/settings','PATCH',{blocked:true},a);
  assert.equal((await call('/api/calls/'+ownerRing.data.id+'/accept','POST',{},c2)).status,403);assert.equal((await call('/api/calls','POST',{type:'voice'},c2)).status,403);assert.equal((await call('/api/admin/calls','POST',{conversationId:id2,type:'voice'},a)).status,403);
  assert.equal((await call('/api/admin/calls/'+ownerRing.data.id,'GET',undefined,a)).data.reason,'blocked');
  await call('/api/admin/conversations/'+id2+'/settings','PATCH',{blocked:false},a);
  const expired=await call('/api/admin/calls','POST',{conversationId:id2,type:'voice'},a);assert.equal(expired.status,201);
  await call('/api/admin/calls/'+expired.data.id+'/signals','POST',offer,a);await db.prepare('UPDATE calls SET expires=? WHERE id=?').bind(Date.now()-1,expired.data.id).run();
  const ended=(await call('/api/calls/'+expired.data.id+'/signals','GET',undefined,c2)).data;assert.equal(ended.call.status,'ended');assert.equal(ended.call.reason,'expired');assert.equal(ended.signals.length,0);
  // Two ringing conversations can exist; only one can become active for Rekha.
  await db.prepare("DELETE FROM rate_limits WHERE key IS NOT NULL").run();
  const ringA=await call('/api/admin/calls','POST',{conversationId:id,type:'voice'},a),ringB=await call('/api/admin/calls','POST',{conversationId:id2,type:'voice'},a);assert.equal(ringA.status,201);assert.equal(ringB.status,201);
  assert.equal((await call('/api/calls/'+ringA.data.id+'/accept','POST',{},c)).status,200);assert.equal((await call('/api/calls/'+ringB.data.id+'/accept','POST',{},c2)).status,409);
  await call('/api/admin/calls/'+ringA.data.id+'/end','POST',{reason:'completed'},a);assert.equal((await call('/api/calls/'+ringB.data.id+'/accept','POST',{},c2)).status,200);
  await call('/api/chat','DELETE',{},c2);assert.equal((await call('/api/admin/calls/'+ringB.data.id,'GET',undefined,a)).status,404);
  console.log('Private call signaling runtime checks passed: authentication and origin checks, customer isolation, opposite-peer SDP/ICE, idempotent descriptions, validation, one active owner call, blocked calls, cancellation, signal expiry/deletion, conversation cascade. Device media connectivity is a separate browser/device test.');
}finally{await mf.dispose();}
